# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `helm-rb` gem.
# Please instead update this file by running `bin/tapioca gem helm-rb`.

module HelmRb
  class << self
    def executable; end
  end
end
