# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kubectl-rb` gem.
# Please instead update this file by running `bin/tapioca gem kubectl-rb`.

module KubectlRb
  class << self
    def executable; end
  end
end
